server:
  port: 7777
spring:
  application:
    name: admin-client-7777
#  boot:
#    admin:
#      client:
#        url: http://localhost:9999 #SpringBoot Admin Server地址
#        instance:
#          name: admin-client-7777

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:1001/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露所有的Actuator端点
  endpoint:
    health:
      show-details: always